export type Urgency = 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW';
export type VolumeBand = 'EXTREME' | 'HEAVY' | 'ELEVATED' | 'MODERATE';

export interface GrievanceRecord {
  id: string;
  source: 'X';
  urgency: Urgency;
  category: string;
  location: string;
  summary: string;
  confidence: number;
  action: string;
  department: string;
  issue: string;
  status: string;
  peopleCount: number;
  complaintCount: number;
  volumeBand: VolumeBand;
  firstReported: string;
  lastReported: string;
  dateKey: string;
  samplePosts: string[];
}

export const mockGrievances: GrievanceRecord[] = [
  {
    id: '#8832',
    source: 'X',
    urgency: 'CRITICAL',
    category: 'Infrastructure',
    location: 'Main Street / School Zone',
    summary: 'Streetlight outage cluster near the school corridor.',
    confidence: 96,
    action: 'Dispatch electrical crew, install temporary lighting, and alert school transport teams.',
    department: 'Public Works',
    issue: 'Repeated complaints indicate a safety-critical lighting outage affecting children and pedestrians after dark.',
    status: 'Awaiting dispatch',
    peopleCount: 186,
    complaintCount: 244,
    volumeBand: 'EXTREME',
    firstReported: 'Apr 16, 2026',
    lastReported: 'Apr 18, 2026',
    dateKey: 'last_24h',
    samplePosts: [
      'School road is dark again and children are walking home in unsafe conditions.',
      'Main Street light poles are dead for the second night in a row.',
      'Parents have been posting about the same blackout near the crossing all evening.',
    ],
  },
  {
    id: '#8835',
    source: 'X',
    urgency: 'CRITICAL',
    category: 'Infrastructure',
    location: 'Market Road Junction',
    summary: 'Pothole cluster disrupting traffic at Market Road Junction.',
    confidence: 94,
    action: 'Send road repair crew, install barricades, and coordinate traffic diversion immediately.',
    department: 'Public Works',
    issue: 'Heavy complaint volume suggests a high-risk traffic choke point with growing accident potential.',
    status: 'Crew assignment needed',
    peopleCount: 172,
    complaintCount: 221,
    volumeBand: 'EXTREME',
    firstReported: 'Apr 15, 2026',
    lastReported: 'Apr 18, 2026',
    dateKey: 'last_24h',
    samplePosts: [
      'Vehicles are swerving around potholes at the junction every few minutes.',
      'Market Road traffic is piling up because the road surface is broken.',
      'This junction has become dangerous during peak hours because of the pothole patch.',
    ],
  },
  {
    id: '#8833',
    source: 'X',
    urgency: 'HIGH',
    category: 'Water',
    location: 'Sector 5 Water Line',
    summary: 'Sector 5 water outage complaints rising across multiple blocks.',
    confidence: 91,
    action: 'Escalate to pipeline maintenance, inspect line pressure, and issue a public water tanker schedule.',
    department: 'Water Department',
    issue: 'Sustained citizen reports indicate a broad utility disruption affecting daily household needs.',
    status: 'Utility review pending',
    peopleCount: 154,
    complaintCount: 198,
    volumeBand: 'HEAVY',
    firstReported: 'Apr 17, 2026',
    lastReported: 'Apr 18, 2026',
    dateKey: 'last_24h',
    samplePosts: [
      'No water in our lane for two days and the issue has spread to nearby apartments.',
      'Families in Sector 5 are still carrying water from outside the area.',
      'More residents are posting that taps are dry all morning and evening.',
    ],
  },
  {
    id: '#8840',
    source: 'X',
    urgency: 'HIGH',
    category: 'Sanitation',
    location: 'Old Town Market',
    summary: 'Waste overflow complaints around Old Town Market are accelerating.',
    confidence: 88,
    action: 'Assign emergency sanitation route, clear overflow points, and disinfect the market perimeter.',
    department: 'Sanitation',
    issue: 'Complaint clustering suggests a hygiene risk in a high-footfall commercial zone.',
    status: 'Supervisor notified',
    peopleCount: 143,
    complaintCount: 176,
    volumeBand: 'HEAVY',
    firstReported: 'Apr 17, 2026',
    lastReported: 'Apr 18, 2026',
    dateKey: 'last_24h',
    samplePosts: [
      'Garbage is overflowing behind the market stalls again.',
      'Shopkeepers are posting photos of piled waste near the entrance.',
      'The smell and flies around Old Town Market are getting worse by the hour.',
    ],
  },
  {
    id: '#8836',
    source: 'X',
    urgency: 'HIGH',
    category: 'Safety',
    location: 'Downtown District',
    summary: 'Signal malfunction reports are concentrated around Downtown crossing.',
    confidence: 89,
    action: 'Route to signal control team and deploy a traffic officer until the lights are stabilized.',
    department: 'Traffic Control',
    issue: 'A rising number of related posts point to unsafe vehicle flow and crossing confusion.',
    status: 'Officer requested',
    peopleCount: 119,
    complaintCount: 149,
    volumeBand: 'HEAVY',
    firstReported: 'Apr 16, 2026',
    lastReported: 'Apr 18, 2026',
    dateKey: 'last_24h',
    samplePosts: [
      'Cars are stopping at random because the signal timing is broken.',
      'Pedestrians are posting that the crossing is unsafe during office hours.',
      'The downtown light keeps blinking instead of cycling normally.',
    ],
  },
  {
    id: '#8837',
    source: 'X',
    urgency: 'MEDIUM',
    category: 'Sanitation',
    location: 'North Park',
    summary: 'Missed garbage pickup complaints are repeating across North Park.',
    confidence: 86,
    action: 'Notify route supervisor, assign recovery pickup, and publish revised collection timing.',
    department: 'Sanitation',
    issue: 'Persistent medium-volume complaints indicate a service reliability issue affecting several streets.',
    status: 'Pending route assignment',
    peopleCount: 88,
    complaintCount: 116,
    volumeBand: 'ELEVATED',
    firstReported: 'Apr 14, 2026',
    lastReported: 'Apr 18, 2026',
    dateKey: 'last_7d',
    samplePosts: [
      'North Park bins are still full even after the scheduled pickup date.',
      'Multiple lanes in the neighborhood have missed collection again.',
      'Residents keep tagging the city because trash is sitting outside homes.',
    ],
  },
  {
    id: '#8838',
    source: 'X',
    urgency: 'MEDIUM',
    category: 'Health',
    location: 'East Side Clinic',
    summary: 'Medicine shortage complaints continue around East Side Clinic.',
    confidence: 83,
    action: 'Forward to health supply coordinator, verify stock levels, and issue a refill ETA.',
    department: 'Health Department',
    issue: 'Medium but consistent citizen volume suggests a service bottleneck rather than a single isolated case.',
    status: 'Verification pending',
    peopleCount: 72,
    complaintCount: 93,
    volumeBand: 'ELEVATED',
    firstReported: 'Apr 12, 2026',
    lastReported: 'Apr 17, 2026',
    dateKey: 'last_7d',
    samplePosts: [
      'Patients are saying the clinic is out of common medicines again.',
      'People are being referred elsewhere because supplies have not arrived.',
      'Several posts mention the same shortage at the East Side counter.',
    ],
  },
  {
    id: '#8841',
    source: 'X',
    urgency: 'MEDIUM',
    category: 'Water',
    location: 'Riverside Ward',
    summary: 'Leakage complaints suggest a growing pipe failure in Riverside Ward.',
    confidence: 82,
    action: 'Send inspection unit, isolate the leak segment, and communicate expected repair timing.',
    department: 'Water Department',
    issue: 'Clustering posts show recurring line leakage and pressure drop across adjacent residential lanes.',
    status: 'Inspection queued',
    peopleCount: 67,
    complaintCount: 84,
    volumeBand: 'ELEVATED',
    firstReported: 'Apr 13, 2026',
    lastReported: 'Apr 18, 2026',
    dateKey: 'last_7d',
    samplePosts: [
      'Water is pooling on the street again and the pressure indoors is dropping.',
      'More houses in Riverside are reporting the same leak and muddy road surface.',
      'Residents are posting videos of continuous pipe leakage near the corner shop.',
    ],
  },
  {
    id: '#8839',
    source: 'X',
    urgency: 'LOW',
    category: 'Infrastructure',
    location: 'River Edge Walkway',
    summary: 'Footpath crack complaints continue along River Edge walkway.',
    confidence: 79,
    action: 'Add to inspection backlog and schedule preventive repair before the monsoon window.',
    department: 'Public Works',
    issue: 'The complaint volume is moderate but stable, indicating preventive maintenance should be scheduled soon.',
    status: 'Backlog review',
    peopleCount: 41,
    complaintCount: 56,
    volumeBand: 'MODERATE',
    firstReported: 'Apr 01, 2026',
    lastReported: 'Apr 16, 2026',
    dateKey: 'older',
    samplePosts: [
      'People jogging on the walkway keep pointing out widening cracks.',
      'The river path is still usable but the damaged sections are increasing.',
      'Residents want repairs before the rainy season makes the footpath worse.',
    ],
  },
  {
    id: '#8842',
    source: 'X',
    urgency: 'LOW',
    category: 'Safety',
    location: 'West End Bus Stop',
    summary: 'Bus shelter lighting complaints are building slowly at West End.',
    confidence: 76,
    action: 'Schedule low-priority electrical maintenance and add the stop to the evening inspection list.',
    department: 'Traffic Control',
    issue: 'Low-frequency but repeated complaints suggest a non-critical commuter comfort and visibility issue.',
    status: 'Scheduled for review',
    peopleCount: 28,
    complaintCount: 39,
    volumeBand: 'MODERATE',
    firstReported: 'Apr 05, 2026',
    lastReported: 'Apr 15, 2026',
    dateKey: 'older',
    samplePosts: [
      'Bus stop lights are dim and people have been posting about it off and on.',
      'Evening commuters say visibility at the shelter is poor.',
      'Not urgent yet, but the stop needs a lighting fix soon.',
    ],
  },
];

export const urgencyRank: Record<Urgency, number> = {
  CRITICAL: 0,
  HIGH: 1,
  MEDIUM: 2,
  LOW: 3,
};

export const volumeRank: Record<VolumeBand, number> = {
  EXTREME: 0,
  HEAVY: 1,
  ELEVATED: 2,
  MODERATE: 3,
};
